### ISSUE TITLE
How to plot NCI plot from outputs of VASP? 

### ISSUE THREAD

**Issue by shwetaphd** [theochem/chemtools#58]
Dear developers,

Please help me with how we can plot NCI plots from POSCAR?

`from chemtools import NCI
nci = NCI.from_file('POSCAR')
nci.generate_plot('poscar')
nci.generate_scripts('poscar')` 

Error: `AttributeError: Atomic Orbitals information is needed!`

Thanks,

**Comment by leila-pujal** [comment]
hi @shwetaphd, sorry for the late reply, and thanks for opening an issue. If I am not mistaken(please correct me if there is a mistake), `POSCAR` is an input file format used for solid-state calculations for VASP. I am not sure how much information this input file contains but with Chemtools, right now it only reads coordinates, atomic numbers, and cellvecs from a POSCAR file. To compute a NCI plot with Chemtools you need to compute the electron density and for that, chemtools loads/uses molecular orbitals information in terms of linear combination of atomic orbitals. The error you are getting is because Chemtools is trying to compute the density but because molecular orbitals information was not read/load from your file that is where the message error is coming from. If you can change file formats, chemtools would be able to generate that plot for any of the formats in [this list](https://iodata.readthedocs.io/en/latest/formats.html#) that loads `mo` and `obasis`. I hope this helps but let me know if you still have questions.

**Comment by PaulWAyers** [comment]
Eventually we could support something that loads a `cube` with density values. It would require using [`Grid`](https://grid.qcdevs.org/) to evaluate the gradient, however.

**Comment by leila-pujal** [comment]
@PaulWAyers, thanks for your comment, that's a good idea. It shouldn't be hard to include this option with the new grid. Now that you have mentioned it, if the starting point is a cube file with the density evaluated, you could use [grid](https://grid.qcdevs.org/) to obtain the gradient and hessian, and then use chemtools to compute the [reduced density gradient](https://github.com/theochem/chemtools/blob/4078cd125e3d0742f4fae2b06f4528ac20161cf2/chemtools/denstools/densbased.py#L123) and then create an NCI class object using the [init method](https://github.com/theochem/chemtools/blob/4078cd125e3d0742f4fae2b06f4528ac20161cf2/chemtools/toolbox/interactions.py#L104) instead of the file. This is all theoretically I have not tried this myself so I am not sure if I am overlooking some incompatibility.

**Comment by shwetaphd** [comment]
Thank you for your reply @leila-pujal ! So I guess if CHGCAR is provided then it may not give this error.
